### ISSUE TITLE
Suppress Cert error on CMX Verify

### ISSUE THREAD

**Issue by hpreston** [CiscoDevNet/dnav3-code#12]
@denapom11 

On this script [https://github.com/CiscoDevNet/dnav3-code/blob/master/verify/backend/cmx.py][https://github.com/CiscoDevNet/dnav3-code/blob/master/verify/backend/cmx.py] 

Please silence the warning about the insecure certificate.

**Comment by denapom11** [comment]
https://github.com/CiscoDevNet/dnav3-code/commit/33c0e904c79e5d1dd634a8710ee6ee0980bade9b
