### ISSUE TITLE
The Mission structure can be made simpler

### ISSUE THREAD

**Issue by Devanampriya** [CiscoDevNet/dnav3-code#30]
I just found 1 instance for simplifying the structure.. the code looks heavy - especially for engineers who are new to programming and are just getting started with python.. so, if possible can we look into reducing the complexity by removing unused and uncalled function blocks and variables?

-o option unnecessarily complicates the structure. 

1) The strict check for -o **will cause an error** as the mission instruction does not ask to give the -o option.. hence the participants will face exit_with_print statement

In step 3 of DNE content as given here https://learninglabs.cisco.com/tracks/dnav3-track/dnav3-meraki/meraki-05-mission/step/3  - it is mentioned  to execute this command : 
```
python mxfirewallcontrol.py -k 6bec40cf957de430a6f1f2baa056b99a4fac9ea0 -c create-backup 
```
The below code will cause the command to exit with print always.. unless you add a dummy orgid or edit the code to keep only the api_key check.

line 471:
```
    if arg_apikey == "" or arg_org == "":
```

2) We are not using it for the mission example as we are parsing all the organization and the networks for taking the backup.

line 477:
```
# compile list of organizations to be processed
    orglist = []
    orgjson = getorglist(arg_apikey)
```

3) There is actually no standard api that will give orgid if we pass the orgname as an argument.. this will unnecessarily trip the participants and make the code more complex.. not to mention that it is not used at all for the mission output.

Line 134:
```
def getorgid(p_apikey, p_orgname):
```

**Comment by denapom11** [comment]
agreed!  pulled per suggestion
