### ISSUE TITLE
CMX Notification Sample Code refers to Meraki API documentation

### ISSUE THREAD

**Issue by bekoeppel** [CiscoDevNet/dnav3-code#37]
The CMX [cmxnotificationreceiver.py](https://github.com/CiscoDevNet/dnav3-code/blob/3a0e8c17e7957933980d569b66cdd38633cf53f1/intro-cmx/cmx-03-notifications-python/cmxnotificationreceiver.py#L10,L11) refers to the Meraki documentation:
> Cisco Meraki CMX Documentation
> https://documentation.meraki.com/MR/Monitoring_and_Reporting/CMX_Analytics#CMX_Location_API

Should probably link to the CMX REST API guide instead:
https://www.cisco.com/c/en/us/td/docs/wireless/mse/10-2/api/b_cmx_102_api_reference.html

**Comment by annegentle** [comment]
Good catch, thanks. Fixed and closing.
