### ISSUE TITLE
line 40 on NETCONF mission answer

### ISSUE THREAD

**Issue by juanda2** [CiscoDevNet/dnav3-code#38]
Hey guys! Would you mind checking line 40 on the [NETCONF lab answer](https://github.com/CiscoDevNet/dnav3-code/blob/solutions/intro-mdp/mission01/netconf_functions.py) ? I believe it should be interfaces instead of interface. Thanks in advance!

**Comment by rnwolfe** [comment]
This is still a problem.. there were multiple PRs for it (#31 and #33) but they never seemed to have been merge.

**Comment by annegentle** [comment]
Yeah, not sure why the forks were deleted, I've now fixed it.
