### ISSUE TITLE
ncclient 0.5.4 doesn't support python 3.7

### ISSUE THREAD

**Issue by rnwolfe** [CiscoDevNet/dnav3-code#44]
See this issue for `ncclient`: https://github.com/ncclient/ncclient/issues/246

The `ncclient` module uses the `async` in its code and it becomes a reserved word in python 3.7. This was fixed in v0.6.x of `ncclient`. 

This ends up breaking the `verify.py` script (and would cause more issues moving forward).

This causes _a lot of hiccups_ in the class when setting up the dev environment as people download 3.7 or already have it. Most were fixing it by re-downloading/installing 3.6, but it is much simpler to update `requirements.txt` to `ncclient` 0.6.2.

I will be submitting a pull request for this.

**Comment by rnwolfe** [comment]
Well, I was going to do a pull request for this, but there already is one: https://github.com/CiscoDevNet/dnav3-code/pull/35

Can we please get this into master to keep the class smooth?

**Comment by annegentle** [comment]
You got it.

**Comment by rnwolfe** [comment]
Awesome! Thanks @annegentle! So quick it was almost automated.. :)

**Comment by annegentle** [comment]
I am robot. 🤖
