### ISSUE TITLE
MDP Mission typo in intro-mdp/mission01/netconf_functions.py

### ISSUE THREAD

**Issue by nerdguru** [CiscoDevNet/dnav3-code#60]
TODO 1 of the MDP mission is to build the parent XML tag correctly, but one of the inner tags has a typo.  Specifically on line 40 of https://github.com/CiscoDevNet/dnav3-code/blob/master/intro-mdp/mission01/netconf_functions.py it currently reads as:

`</interface>`

should be

`</interfaces>`

An XML/Pyton noob might trip up on that.  I'll submit a PR.

**Comment by annegentle** [comment]
Weird, thought this was fixed with https://github.com/rnwolfe/dnav3-code/commit/e71fcb62e02bebd39a3a4da6dfaa2b4cf188f76a. Merging.
